config/routes.rb
Rails.application.routes.draw do
  get '/data', to: 'data#create'
  post '/data', to: 'data#create'

  root to: 'data#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_table.rb
class DataTable < ApplicationRecord
  def self.clean!
    all.order(created_at: :desc).offset(5999).delete_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def index
    @records = DataTable.all.order(created_at: :desc)
  end

  def create
    DataTable.clean!
    @record = DataTable.create data: params.try(:to_s)
    head :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/data/create.html.erb
<%= @record.data %>

app/views/data/index.html.erb
Data Endpoint: <%= data_url %>
<br>
<br>
<% @records.each do |record| %>
  <%= record.id %>&nbsp;<%= record.data %><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataLogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>